server {
    listen 80;
    server_name localhost;

    client_max_body_size 100m;

    location /api/ {
        proxy_pass http://backend:8000/;
        include /etc/nginx/snippets/proxy-params.conf;
    }

    location /health {
        proxy_pass http://backend:8000/health;
        include /etc/nginx/snippets/proxy-params.conf;
    }

    location / {
        proxy_pass http://frontend:3000;
        include /etc/nginx/snippets/proxy-params.conf;
    }
}
